name = "Niceandeasy"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "https://github.com/jforman/niceandeasy/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Jeffrey Forman"
  homepage = "https://github.com/jforman/niceandeasy/"
